version: '3.4'

services:
  service1_web:
    image: demo1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9999:80"
  service2_web:
    image: httpd
    build: .
    ports:
      - "7777:80"