apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - myapp
        topologyKey: kubernetes.io/hostname
  containers:
  - name: con1
    image: nginx
